name: Count 'a' Character

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  count_a_character:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run 'a' character count
        run: |
          rake user:count_a_character
